### ISSUE TITLE
Call to a member function exists() on null

### ISSUE THREAD

**Issue by lloyd966** [cornernote/yii2-return-url#3]
Hi,

I install your yii2-returnurl  with composer. I am geting the following error Call to a member function exists() on null

I place the following code in my Project/views/index.php file.

use cornernote\returnurl\returnurl;
Html::a('<i class="glyphicon glyphicon-plus"></i> Add', ['create'], ['class' => 'btn btn-success', 'ru' => ReturnUrl::getToken()])

and on the error page it shows the following

in D:\wamp64\www\pmtts\vendor\cornernote\yii2-returnurl\src\ReturnUrl.php at line 45– cornernote\returnurl\ReturnUrl::urlToToken('/pmtts/web/index.php?r=projects%...')

so it seems as that a value is being passed.

Any help in getting this to work would be greatly appreciated.

Lloyd

**Comment by cornernote** [comment]
What's in Yii::$app->request->url ?

**Comment by lloyd966** [comment]
I am not sure if this is what you but below is what shows in browser

http://localhost/pmtts/web/index.php?r=projects%2Findex

**Comment by lloyd966** [comment]
where are you located?  maybe we can setup a zoom meeting or sykpe to discuss

**Comment by lloyd966** [comment]
added this code to my project index view    echo Yii::$app->request->url 
and it displayed the following:

/pmtts/web/index.php?r=projects%2Findex


hope this helps

**Comment by lloyd966** [comment]
Problem Fixed

Turns out I have commented out the  following in my config file

//'cache' => [
//    'class' => 'yii\caching\FileCache',
//],

When I remove the comments (ie //),  i do not get the error.

May I suggest that as part of your install and usage in the readme, that you add instructions to
for adding the cache code to the config, and the use statement use cornernote\returnurl\returnurl; 
to those views and controllers that use your methods.

Thank you for your quick reply to my original comment

Lloyd

**Comment by cornernote** [comment]
I have added Requirements to the README.md.

Thanks!
